[2021-04-06 22:50:37,028] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: process_financials.process_data 2021-04-06T22:50:35.550487+00:00 [queued]>
[2021-04-06 22:50:37,092] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: process_financials.process_data 2021-04-06T22:50:35.550487+00:00 [queued]>
[2021-04-06 22:50:37,093] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-06 22:50:37,093] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-04-06 22:50:37,094] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-06 22:50:37,150] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): process_data> on 2021-04-06T22:50:35.550487+00:00
[2021-04-06 22:50:37,154] {standard_task_runner.py:52} INFO - Started process 506 to run task
[2021-04-06 22:50:37,161] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'process_financials', 'process_data', '2021-04-06T22:50:35.550487+00:00', '--job-id', '8', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/learn_operators.py', '--cfg-path', '/tmp/tmp7d0k6ot6', '--error-file', '/tmp/tmpzbpotmeg']
[2021-04-06 22:50:37,164] {standard_task_runner.py:77} INFO - Job 8: Subtask process_data
[2021-04-06 22:50:37,245] {logging_mixin.py:104} INFO - Running <TaskInstance: process_financials.process_data 2021-04-06T22:50:35.550487+00:00 [running]> on host ce03b876977a
[2021-04-06 22:50:37,332] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=ozbaya@airflow.com
AIRFLOW_CTX_DAG_OWNER=ozbaya
AIRFLOW_CTX_DAG_ID=process_financials
AIRFLOW_CTX_TASK_ID=process_data
AIRFLOW_CTX_EXECUTION_DATE=2021-04-06T22:50:35.550487+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-06T22:50:35.550487+00:00
[2021-04-06 22:50:37,343] {taskinstance.py:1455} ERROR - 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/learn_operators.py", line 25, in _process_data
    ret = process_financials_data()
  File "/opt/airflow/dags/utils/parser.py", line 78, in process_financials_data
    script = soup.find("script",text=re.compile("root.App.main")).text
AttributeError: 'NoneType' object has no attribute 'text'
[2021-04-06 22:50:37,347] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=process_financials, task_id=process_data, execution_date=20210406T225035, start_date=20210406T225037, end_date=20210406T225037
[2021-04-06 22:50:37,441] {local_task_job.py:146} INFO - Task exited with return code 1
